Import( 'env', 'libs', 'installdir', 'testdir' )

sources = [ 	"AdminCommandHandler.cpp",
		"AdminCommandManager.cpp",
		"AuthManager.cpp",
		"BinaryDataResponse.cpp",
		"BinaryIncomingData.cpp",
		"BroadcastListener.cpp",
		"BroadcastThread.cpp",
		"FileSendData.cpp",
		"Folder.cpp",
		"FolderListHandlers.cpp",
		"FolderMan.cpp",
		"HandshakeHandlers.cpp",
		"main.cpp",
		"PBRequestHandler.cpp",
		"PBResponseSendHandler.cpp",
		"ServerComms.cpp",
		"SyncroDB.cpp",
		"SyncroPBResponseFactory.cpp",
		"SyncroServer.cpp",
		"FileHashHandlers.cpp",
		"VectorPBResponse.cpp",
		"FolderContentsHandlers.cpp" ]

output = env.Program( 'syncro', source = sources, LIBS=libs )

env.Install( installdir, output )
env.Install( testdir, output )
