Import( 'env', 'libs', 'testdir' )

mylibs = libs + [ 'cppunit' ]

sources = [ 
	"main.cpp", 
	"SystemTest.cpp",
	"TestDatabase.cpp",
	"../../../Syncro Server/src/SyncroDB.cpp"
	]

output = env.Program( 
	target = 'SystemTest',
	source = sources,
	LIBS=mylibs
	)

env.Install( testdir, output )
