Import( 'env', 'libs', 'installdir' )

mylibs = libs + [ 'cppunit' ]

sources = [ 
	"main.cpp", 
	"SystemTest.cpp",
	"TestDatabase.cpp",
	"../../../Syncro Server/src/SyncroDB.cpp"
	]

output = env.Program( 
	target = 'SystemTest',
	source = sources,
	LIBS=mylibs
	)

#TODO: Fix this install statement, may not work as i want...
env.Install( installdir, output )
