Import( 'env', 'libs', 'testdir', 'platform', 'debug' )

if ( platform == 'win32' ) and int(debug):
	mylibs = libs + [ 'cppunitd' ]
else:
	mylibs = libs + [ 'cppunit' ]

sources = [ 
	"main.cpp", 
	"SystemTest.cpp",
	"TestDatabase.cpp",
	"../../../Syncro Server/src/SyncroDB.cpp"
	]

output = env.Program( 
	target = 'SystemTest',
	source = sources,
	LIBS=mylibs
	)

installoutput = env.Install( testdir, output )
env.Alias( 'SystemTest', installoutput )
