// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "admin.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace syncro {
namespace pb {

void protobuf_ShutdownFile_admin_2eproto() {
  delete GenericAdminCommand::default_instance_;
  delete AdminAck::default_instance_;
}

void protobuf_AddDesc_admin_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  GenericAdminCommand::default_instance_ = new GenericAdminCommand();
  AdminAck::default_instance_ = new AdminAck();
  GenericAdminCommand::default_instance_->InitAsDefaultInstance();
  AdminAck::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_admin_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_admin_2eproto {
  StaticDescriptorInitializer_admin_2eproto() {
    protobuf_AddDesc_admin_2eproto();
  }
} static_descriptor_initializer_admin_2eproto_;


// ===================================================================

const ::std::string GenericAdminCommand::_default_command_;
const ::std::string GenericAdminCommand::_default_param_;
#ifndef _MSC_VER
const int GenericAdminCommand::kCommandFieldNumber;
const int GenericAdminCommand::kParamFieldNumber;
#endif  // !_MSC_VER

GenericAdminCommand::GenericAdminCommand()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void GenericAdminCommand::InitAsDefaultInstance() {
}

GenericAdminCommand::GenericAdminCommand(const GenericAdminCommand& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void GenericAdminCommand::SharedCtor() {
  _cached_size_ = 0;
  command_ = const_cast< ::std::string*>(&_default_command_);
  param_ = const_cast< ::std::string*>(&_default_param_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GenericAdminCommand::~GenericAdminCommand() {
  SharedDtor();
}

void GenericAdminCommand::SharedDtor() {
  if (command_ != &_default_command_) {
    delete command_;
  }
  if (param_ != &_default_param_) {
    delete param_;
  }
  if (this != default_instance_) {
  }
}

void GenericAdminCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const GenericAdminCommand& GenericAdminCommand::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_admin_2eproto();  return *default_instance_;
}

GenericAdminCommand* GenericAdminCommand::default_instance_ = NULL;

GenericAdminCommand* GenericAdminCommand::New() const {
  return new GenericAdminCommand;
}

void GenericAdminCommand::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (_has_bit(0)) {
      if (command_ != &_default_command_) {
        command_->clear();
      }
    }
    if (_has_bit(1)) {
      if (param_ != &_default_param_) {
        param_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool GenericAdminCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string command = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_command()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_param;
        break;
      }
      
      // optional string param = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_param:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_param()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void GenericAdminCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string command = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->command(), output);
  }
  
  // optional string param = 2;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->param(), output);
  }
  
}

int GenericAdminCommand::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string command = 1;
    if (has_command()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->command());
    }
    
    // optional string param = 2;
    if (has_param()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->param());
    }
    
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GenericAdminCommand::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const GenericAdminCommand*>(&from));
}

void GenericAdminCommand::MergeFrom(const GenericAdminCommand& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_command(from.command());
    }
    if (from._has_bit(1)) {
      set_param(from.param());
    }
  }
}

void GenericAdminCommand::CopyFrom(const GenericAdminCommand& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GenericAdminCommand::IsInitialized() const {
  
  return true;
}

void GenericAdminCommand::Swap(GenericAdminCommand* other) {
  if (other != this) {
    std::swap(command_, other->command_);
    std::swap(param_, other->param_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string GenericAdminCommand::GetTypeName() const {
  return "syncro.pb.GenericAdminCommand";
}


// ===================================================================

#ifndef _MSC_VER
const int AdminAck::kOkFieldNumber;
const int AdminAck::kErrorCodeFieldNumber;
#endif  // !_MSC_VER

AdminAck::AdminAck()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void AdminAck::InitAsDefaultInstance() {
}

AdminAck::AdminAck(const AdminAck& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void AdminAck::SharedCtor() {
  _cached_size_ = 0;
  ok_ = false;
  error_code_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AdminAck::~AdminAck() {
  SharedDtor();
}

void AdminAck::SharedDtor() {
  if (this != default_instance_) {
  }
}

void AdminAck::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const AdminAck& AdminAck::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_admin_2eproto();  return *default_instance_;
}

AdminAck* AdminAck::default_instance_ = NULL;

AdminAck* AdminAck::New() const {
  return new AdminAck;
}

void AdminAck::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    ok_ = false;
    error_code_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool AdminAck::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool ok = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &ok_)));
          _set_bit(0);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_error_code;
        break;
      }
      
      // optional int32 error_code = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_error_code:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
          _set_bit(1);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void AdminAck::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bool ok = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->ok(), output);
  }
  
  // optional int32 error_code = 2;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->error_code(), output);
  }
  
}

int AdminAck::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool ok = 1;
    if (has_ok()) {
      total_size += 1 + 1;
    }
    
    // optional int32 error_code = 2;
    if (has_error_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->error_code());
    }
    
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AdminAck::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const AdminAck*>(&from));
}

void AdminAck::MergeFrom(const AdminAck& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_ok(from.ok());
    }
    if (from._has_bit(1)) {
      set_error_code(from.error_code());
    }
  }
}

void AdminAck::CopyFrom(const AdminAck& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AdminAck::IsInitialized() const {
  
  return true;
}

void AdminAck::Swap(AdminAck* other) {
  if (other != this) {
    std::swap(ok_, other->ok_);
    std::swap(error_code_, other->error_code_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string AdminAck::GetTypeName() const {
  return "syncro.pb.AdminAck";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace syncro

// @@protoc_insertion_point(global_scope)
