
#cpppath = [ "include", "../../kode/include/", "../../libsyncro/include/", "../../libsyncro/include/libsyncro/protocol_buffers", "../../../Dependencies/protobuf-2.3.0/include", "../../../Dependencies/sqlite/", "../../../Dependencies/tinyxml/" ] 

#libpath = [ "/usr/lib", "/usr/local/lib" ] 

#libs = [ 'syncro', 'kode', 'tinyxml', 'sqlite', 'pthread', 'stdc++', 'c', 'dl', 'boost_system', 'boost_thread', 'boost_filesystem', 'boost_regex', 'boost_date_time', 'protobuf-lite' ]

#VariantDir( 'build', 'c', duplicate=0 )
#env = Environment( CPPPATH = cpppath, LIBPATH=libpath )

SConscript( 'tinyxml/SConscript' ) 
