Import( 'libs', 'env', 'installdir' )

output = env.Program( 
	target = 'SyncroAdmin',
	source = ['SyncroAdmin.cpp'],
	LIBS=libs
	)

installoutput = env.Install( installdir, output )
env.Alias( 'SyncroAdmin', installoutput )
