#
#

cpppath = [ 
	"include", 
	"../../kode/include/", 
	"../../libsyncro/include/", 
	"../../libsyncro/include/libsyncro/protocol_buffers" 
	] 

libpath = [ 
	"../../kode/", 
	"../../libsyncro/" 
	] 

libs = [ 
	'syncro', 
	'kode', 
	'sqlite3', 
	'boost_system', 
	'boost_thread', 
	'boost_filesystem', 
	'boost_regex', 
	'boost_date_time', 
	'boost_program_options',
	'protobuf-lite', 
	'crypto++' 
	]

cppdefines = [ "_LINUX" ];
ccflags = [];

env = Environment()

debug = ARGUMENTS.get( 'debug', 0 )

builddir='build_release'

if int(debug):
	cppdefines += [ '_DEBUG' ]
	ccflags += [ '-g' ]
	builddir='build_debug'

env.Append( 
	CPPPATH = cpppath, 
	LIBPATH=libpath, 
	LIBS=libs,
	CPPDEFINES=cppdefines,
	CCFLAGS=ccflags
	)

SConscript( 'src/SConscript', exports='env libs', variant_dir=builddir, duplicate=0 )
