// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

package uk.me.grambo.syncro.pb;

public final class Header {
  private Header() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public static final class PacketHeader extends
      com.google.protobuf.GeneratedMessageLite {
    // Use PacketHeader.newBuilder() to construct.
    private PacketHeader() {
      initFields();
    }
    private PacketHeader(boolean noInit) {}
    
    private static final PacketHeader defaultInstance;
    public static PacketHeader getDefaultInstance() {
      return defaultInstance;
    }
    
    public PacketHeader getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // required int32 packet_type = 1;
    public static final int PACKET_TYPE_FIELD_NUMBER = 1;
    private boolean hasPacketType;
    private int packetType_ = 0;
    public boolean hasPacketType() { return hasPacketType; }
    public int getPacketType() { return packetType_; }
    
    // repeated int32 subpacket_sizes = 2;
    public static final int SUBPACKET_SIZES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> subpacketSizes_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getSubpacketSizesList() {
      return subpacketSizes_;
    }
    public int getSubpacketSizesCount() { return subpacketSizes_.size(); }
    public int getSubpacketSizes(int index) {
      return subpacketSizes_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasPacketType) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPacketType()) {
        output.writeInt32(1, getPacketType());
      }
      for (int element : getSubpacketSizesList()) {
        output.writeInt32(2, element);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPacketType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getPacketType());
      }
      {
        int dataSize = 0;
        for (int element : getSubpacketSizesList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getSubpacketSizesList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    public static uk.me.grambo.syncro.pb.Header.PacketHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.me.grambo.syncro.pb.Header.PacketHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.me.grambo.syncro.pb.Header.PacketHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static uk.me.grambo.syncro.pb.Header.PacketHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static uk.me.grambo.syncro.pb.Header.PacketHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.me.grambo.syncro.pb.Header.PacketHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static uk.me.grambo.syncro.pb.Header.PacketHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.me.grambo.syncro.pb.Header.PacketHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static uk.me.grambo.syncro.pb.Header.PacketHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static uk.me.grambo.syncro.pb.Header.PacketHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(uk.me.grambo.syncro.pb.Header.PacketHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          uk.me.grambo.syncro.pb.Header.PacketHeader, Builder> {
      private uk.me.grambo.syncro.pb.Header.PacketHeader result;
      
      // Construct using uk.me.grambo.syncro.pb.Header.PacketHeader.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new uk.me.grambo.syncro.pb.Header.PacketHeader();
        return builder;
      }
      
      protected uk.me.grambo.syncro.pb.Header.PacketHeader internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new uk.me.grambo.syncro.pb.Header.PacketHeader();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public uk.me.grambo.syncro.pb.Header.PacketHeader getDefaultInstanceForType() {
        return uk.me.grambo.syncro.pb.Header.PacketHeader.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public uk.me.grambo.syncro.pb.Header.PacketHeader build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private uk.me.grambo.syncro.pb.Header.PacketHeader buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public uk.me.grambo.syncro.pb.Header.PacketHeader buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.subpacketSizes_ != java.util.Collections.EMPTY_LIST) {
          result.subpacketSizes_ =
            java.util.Collections.unmodifiableList(result.subpacketSizes_);
        }
        uk.me.grambo.syncro.pb.Header.PacketHeader returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(uk.me.grambo.syncro.pb.Header.PacketHeader other) {
        if (other == uk.me.grambo.syncro.pb.Header.PacketHeader.getDefaultInstance()) return this;
        if (other.hasPacketType()) {
          setPacketType(other.getPacketType());
        }
        if (!other.subpacketSizes_.isEmpty()) {
          if (result.subpacketSizes_.isEmpty()) {
            result.subpacketSizes_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.subpacketSizes_.addAll(other.subpacketSizes_);
        }
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              setPacketType(input.readInt32());
              break;
            }
            case 16: {
              addSubpacketSizes(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addSubpacketSizes(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // required int32 packet_type = 1;
      public boolean hasPacketType() {
        return result.hasPacketType();
      }
      public int getPacketType() {
        return result.getPacketType();
      }
      public Builder setPacketType(int value) {
        result.hasPacketType = true;
        result.packetType_ = value;
        return this;
      }
      public Builder clearPacketType() {
        result.hasPacketType = false;
        result.packetType_ = 0;
        return this;
      }
      
      // repeated int32 subpacket_sizes = 2;
      public java.util.List<java.lang.Integer> getSubpacketSizesList() {
        return java.util.Collections.unmodifiableList(result.subpacketSizes_);
      }
      public int getSubpacketSizesCount() {
        return result.getSubpacketSizesCount();
      }
      public int getSubpacketSizes(int index) {
        return result.getSubpacketSizes(index);
      }
      public Builder setSubpacketSizes(int index, int value) {
        result.subpacketSizes_.set(index, value);
        return this;
      }
      public Builder addSubpacketSizes(int value) {
        if (result.subpacketSizes_.isEmpty()) {
          result.subpacketSizes_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.subpacketSizes_.add(value);
        return this;
      }
      public Builder addAllSubpacketSizes(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.subpacketSizes_.isEmpty()) {
          result.subpacketSizes_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.subpacketSizes_);
        return this;
      }
      public Builder clearSubpacketSizes() {
        result.subpacketSizes_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:syncro.pb.PacketHeader)
    }
    
    static {
      defaultInstance = new PacketHeader(true);
      uk.me.grambo.syncro.pb.Header.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:syncro.pb.PacketHeader)
  }
  
  
  static {
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
