Import( 'env', 'libtargetdir' )

sources = [ 
	'src/Database.cpp', 
	'src/utils.cpp', 
	'src/tcpconnection.cpp', 
	'src/stopwatch.cpp',
	'src/db/dbutils.cpp',
	'src/db/statement.cpp'
	 ]

output = env.StaticLibrary( 'kode', sources )

installoutput = env.Install( libtargetdir ,output )
env.Alias( 'kode', installoutput )

SConscript( 'test/SConscript' )
