
cpppath = [ "include", "include/kode", "../../Dependencies/sqlite/", ] 

VariantDir( 'build/', 'src/', duplicate=0 )

env = Environment( CPPPATH = cpppath )


sources = [ 'src/Database.cpp', 'src/utils.cpp', 'src/tcpconnection.cpp', 'src/stopwatch.cpp' ]

env.StaticLibrary( 'kode', sources )
