
cpppath = [ "../../../kode/include/", "../../../libsyncro/include/", "../../../libsyncro/include/libsyncro/protocol_buffers" ] 

libpath = [ "../../../kode/", "../../../libsyncro/" ] 

libs = [ 'syncro', 'kode', 'sqlite3', 'boost_system', 'boost_thread', 'boost_filesystem', 'boost_date_time', 'protobuf-lite', 'boost_program_options', 'libcrypto++', 'cppunit' ]

#VariantDir( 'build', 'c', duplicate=0 )
env = Environment( CPPPATH = cpppath, LIBPATH=libpath, LIBS=libs )

#env.Program( target = 'SystemTest', source = sources )

SConscript( 'src/SConscript', exports='env libs', variant_dir='build_release', duplicate=0 )
